name: Release Process
on:
  push:
    branches:
      - main
  workflow_dispatch: 
env:
  current_version: 0.1.13
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          echo "Running tests..."

  bump-version:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version
        run: ./bump-version.sh ${{ env.current_version }}
      - name: Create Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GitHub token
        run: |
          VERSION=$(cat VERSION)
          git tag v$VERSION
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/tvangundy/rp-blueprint.git v$VERSION

  create-release:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.ref_name }}
          draft: true  # Requires manual approval

  publish-release:
    needs: create-release
    runs-on: ubuntu-latest
    environment: production  # Requires manual approval
    steps:
      - uses: actions/checkout@v3
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.ref_name }}
          draft: false
