name: Release Process
on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          echo "Running tests..."

  bump-version:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version
        run: ./bump-version.sh
      - name: Create Git Tag
        run: |
          VERSION=$(cat VERSION)
          git tag v$VERSION
          git push origin v$VERSION

  create-release:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.ref_name }}
          draft: true  # Requires manual approval

  publish-release:
    needs: create-release
    runs-on: ubuntu-latest
    environment: production  # Requires manual approval
    steps:
      - uses: actions/checkout@v3
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.ref_name }}
          draft: false
