name: Validate All Repositories
# on:
#   workflow_dispatch:  # Enables manual trigger from GitHub UI
#   repository_dispatch:  # Triggered automatically by dependent repositories
#     types: [test-trigger]

on:
  push:
    branches:
      - main
      
  # workflow_dispatch:
  #   inputs:
  #     confirm:
  #       description: 'Type "YES" to approve release'
  #       required: true
  #       default: 'NO'

  repository_dispatch:
    types: [trigger-tests]  # Listens for this event type
  workflow_dispatch:  # Allows manual trigger via Actions tab

jobs:

  # Verify Approval
  verify_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Approval
        run: |
          echo "Current version: ${{ env.current_version }}"
          echo "Operating System: $(uname -s)"
          echo "Platform: $(uname -m)"
          if [ "${{ github.event.inputs.confirm }}" != "YES" ]; then
            echo "Approval not given. Exiting."
            exit 1
          fi

  test-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout windsortest
        uses: actions/checkout@v3

      - name: Clone latest main branches of dependencies
        run: |
          echo "Cloning core"
          # git clone --depth 1 --branch main https://github.com/YOUR_ORG/core.git
          # git clone --depth 1 --branch main https://github.com/YOUR_ORG/cli.git
          # git clone --depth 1 --branch main https://github.com/YOUR_ORG/app.git

      - name: Run integration tests
        run: |
          echo "Running integration tests"
          #   ./run-integration-tests.sh

  approve-release:
    needs: test-dependencies
    runs-on: ubuntu-latest
    environment: manual-approval  # Requires manual confirmation
    steps:
      - name: Approve release
        run: echo "All tests passed. Ready for tagging."
